### ISSUE TITLE
Could not pass event PlayerJoinEvent to GodsEye vBuild 27 BETA

### ISSUE THREAD

**Issue by UnknownName404** [Nort721/GodsEye-Issues#118]
A bug report/issue report should contain:

1) GodsEye version (BUILD 27 BETA)
2) Server Version+Fork (1.15.2 paper 129)
3) ProtocolLib version (4.5.0)

```
[19:12:55 ERROR]: Could not pass event PlayerJoinEvent to GodsEye vBuild 27 BETA
java.lang.NullPointerException: null
at godseye.fZ.a(fZ.java:47) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor487.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-129]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-129]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-129]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-129]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
>.... [19:12:55 INFO]: CR33PYEL[/90.65.58.69:51343] logged in with entity id 156870 at ([world]-2532.0281526879758, 72.0, 562.1193851302954)
>.... [19:12:55 INFO]: [+] CR33PYEL nous a rejoints ! 

```
This error occurred when a player joined the server

**Comment by Nort721** [comment]
Since I can't really replicate this error, I did some changes that should fix it, if after next update you're still having this issue, contact me and I will reopen this issue
