### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by DaffyDG** [Nort721/GodsEye-Issues#128]
A bug report/issue report should contain:

1) GodsEye version
2) Server Version+Fork
3) ProtocolLib version
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue

**Comment by DaffyDG** [comment]
[13:42:12 WARN]: [GodsEye] Task #36 for GodsEye vBuild 29 BETA generated an exception
java.lang.IllegalStateException: Start block missed in BlockIterator

**Comment by DaffyDG** [comment]
Full Error
[13:42:12 WARN]: [GodsEye] Task #36 for GodsEye vBuild 29 BETA generated an exception
java.lang.IllegalStateException: Start block missed in BlockIterator
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:170) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:233) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:268) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:160) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:195) ~[server.jar:git-Spigot-db6de12-18fbb24]
at godseye.et.n(et.java:174) ~[?:?]
at godseye.i.run(i.java:18) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
