### ISSUE TITLE
GodsEye-Sync: don't want to connect to mysql (starts with Docker)

### ISSUE THREAD

**Issue by iverly** [Nort721/GodsEye-Issues#160]
Hey,

GodsEye version: Build 30 BETA
GodsEye-Sync: 1.0.2

This is a know issue from many others plugins. The official mysql latest version for Docker don't use latin1 as the default encoding and thrown an error.

```
[11:16:58 ERROR]: Can't connect to MySQL database,database features are now disabled
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2239) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_212]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_212]
	at it.goodtimes14.godseye.mysql.Database.<init>(Database.java:34) [GodsEyeSync-Bukkit.jar:?]
	at it.goodtimes14.godseye.GodsEyeSync.onEnable(GodsEyeSync.java:39) [GodsEyeSync-Bukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.sql.SQLException: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.ConnectionImpl.configureClientCharacterSet(ConnectionImpl.java:1794) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3523) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2202) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	... 25 more
```

To fix this issues, please add `?characterEncoding=latin1` at the end of the connection URI.

**Comment by Nort721** [comment]
You should report this to the developer of GodsEyeSync then, GoodTimes14ita#6884
