### ISSUE TITLE
Big Error on my console

### ISSUE THREAD

**Issue by Mariopg03** [Nort721/GodsEye-Issues#239]
1) GodsEye version | BETA 36

2) Server Version+Fork | TacoSpigot, PaperSpigot Fork, Version 1.12.2

3) ProtocolLib version | 4.5.1

4) Server log | 

[13:14:39 ERROR]: [GodsEye] Unhandled exception occured in onPacketReceiving(PacketEvent) for GodsEye
java.lang.UnsupportedOperationException: The method getAllowFlight is not supported for temporary players.
        at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$e35c185c.getAllowFlight(<generated>) ~[?:?]
        at godseye.m.a(m.java:148) ~[GodsEye.jar:?]
        at godseye.bF.onPacketReceiving(bF.java:204) ~[GodsEye.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:350) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:315) [ProtocolLib.jar:4.5.1]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:538) [ProtocolLib.jar:4.5.1]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) [ProtocolLib.jar:4.5.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24) [ProtocolSupport-1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerCo        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) [ProtocolLib.jar:4.5.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24) [ProtocolSupport-1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) [ProtocolSupport-1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [PrisionOP.jar:git-TacoSpigot-"f8ba67d6"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[13:14:39 ERROR]: Parameters:
  net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload@711a1fde[
    a=REGISTER
    b=PooledUnsafeDirectByteBuf(ridx: 0, widx: 122, cap: 122)
  ]

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
![Sin título](https://user-images.githubusercontent.com/46244100/89708851-f8b3ec80-d97a-11ea-96b2-a152b6cd787c.png)

6) A very detailed description of the issue | Big Error in my console, i don't know why

**Comment by Nort721** [comment]
Please create a pastebin of the error, just pasting it like that or providing a picture does not help much

**Comment by Mariopg03** [comment]
https://pastebin.com/QE2Cn2JD

**Comment by Nort721** [comment]
Did you download the 1.8 - 1.15 ProtocolLib?
