### ISSUE TITLE
Plugin disabled

### ISSUE THREAD

**Issue by Zeta314** [Nort721/GodsEye-Issues#31]
- CraftBukkit version git-Spigot-94af569-a3fdef8 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
- 4.5.0-SNAPSHOT
```
27.09 23:59:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
27.09 23:59:17 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'ge' in plugin GodsEye vBuild 13 BETA (HotFix-2) - plugin is disabled.
```

- Basically, after restarting the server, I type /eg and it throws that error.

**Comment by Nort721** [comment]
There error you sent here is not related to GodsEye

**Comment by Nort721** [comment]
it may be a problem with your license, it should be fixed now

**Comment by Zeta314** [comment]
```
28.09 08:21:11 [Server] INFO ... 8 more
28.09 08:21:11 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
28.09 08:21:11 [Server] INFO at godseye.aJ.onCommand(aJ.java:19) ~[?:?]
28.09 08:21:11 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
28.09 08:21:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
28.09 08:21:11 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
28.09 08:21:11 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
28.09 08:21:11 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:394) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
28.09 08:21:11 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:430) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
28.09 08:21:11 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:695) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
28.09 08:21:11 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
28.09 08:21:11 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
28.09 08:21:11 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
28.09 08:21:11 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ge' in plugin GodsEye vBuild 13 BETA (HotFix-2)
28.09 08:21:11 [Server] Server thread/WARN Unexpected exception while parsing console command "ge"
```

I think that's not fixed. Any suggestion?
