### ISSUE TITLE
Bug that occurs when using GodsEye and ViaVersion 5.0 at the same time

### ISSUE THREAD

**Issue by morlef** [Nort721/GodsEye-Issues#494]
A bug report should contain:

1) GodsEye version
  Build 64
2) Server Version+Fork
  Paper 1.16.5#794
3) Client Version+Fork
  1.21
4) ProtocolLib version
  5.3.0-SNAPSHOT-720
5) Console errors if there are any (using pastebin.com)
Could not pass event PlayerJoinEvent to GodsEye vBuild 64
java.lang.NoClassDefFoundError: us/myles/ViaVersion/api/Via
        at godseye.W.<init>(W.java:41) ~[?:?]
        at godseye.q.a(q.java:19) ~[?:?]
        at godseye.a9.a(a9.java:42) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor386.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:356) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:303) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1520) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: us.myles.ViaVersion.api.Via
        ... 19 more
6) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
  Logs only
7) A very detailed description of the issue
Every time some GodsEye related event fires, an error occurs that the ViaVersion API class is missing.

**Comment by morlef** [comment]
uses ViaVersion-5.0.1.jar

**Comment by morlef** [comment]
The bug was caused by the removal of the ViaVersion [legacy api](https://github.com/ViaVersion/ViaVersion/blob/4.10.2/api-legacy/src/main/java/us/myles/ViaVersion/api/Via.java).
At the bottom of the API changes in the [5.0.0 release notes](https://github.com/ViaVersion/ViaVersion/releases/tag/5.0.0), it says "Removed a number of deprecated methods".
