### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Riiiiiiiiiiiiiiiiiiiiii** [Nort721/GodsEye-Issues#85]
[19:54:58] [Server thread/ERROR]: [GodsEye] Unhandled exception occured in onPacketSending(PacketEvent) for GodsEye
java.lang.UnsupportedOperationException: The method getAllowFlight is not supported for temporary players.
at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[ProtocolLib.jar:?]
at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$b26fbd26.getAllowFlight(<generated>) ~[?:?]
at godseye.cN.c(cN.java:132) ~[GodsEye.jar:?]
at godseye.dr.onPacketSending(dr.java:149) ~[GodsEye.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:?]
at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:185) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:155) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1394) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1367) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.PlayerConnection.internalTeleport(PlayerConnection.java:1113) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1057) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1041) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1032) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:165) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:154) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:220) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1092) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot.jar:git-Spigot-9de398a-9c887d4]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot.jar:git-Spigot-9de398a-9c887d4]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[19:54:58] [Server thread/ERROR]: Parameters:
net.minecraft.server.v1_14_R1.PacketPlayOutPosition@518436e0[
a=-60.309266625892135
b=11.0
c=-69.13325769523405
d=185.20084
e=14.150553
f=[]
g=1

**Comment by Nort721** [comment]
Hey, please do not ignore the information requested in the issue, I'm closing this issue please open another one and fill up the information thats requested and use pastebin!

**Comment by Nort721** [comment]
Closed do to lack of info
