### ISSUE TITLE
Serious error

### ISSUE THREAD

**Issue by Riiiiiiiiiiiiiiiiiiiiii** [Nort721/GodsEye-Issues#87]
[01:04:10] [Netty Server IO #1/ERROR]: [GodsEye] Unhandled exception occured in onPacketReceiving(PacketEvent) for GodsEye
java.lang.UnsupportedOperationException: The method getAllowFlight is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$72f69d40.getAllowFlight(<generated>) ~[?:?]
	at godseye.cN.c(cN.java:132) ~[GodsEye.jar:?]
	at godseye.dr.onPacketReceiving(dr.java:143) ~[GodsEye.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:506) [ProtocolLib.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:245) [ProtocolLib.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[01:04:10] [Netty Server IO #1/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayInSettings@23d72729[
    a=zh_tw
    viewDistance=12
    c=FULL
    d=true
    e=127
    f=Right
  ]
[01:04:10] [Netty Server IO #1/ERROR]: [GodsEye] Unhandled exception occured in onPacketReceiving(PacketEvent) for GodsEye
java.lang.UnsupportedOperationException: The method getAllowFlight is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$72f69d40.getAllowFlight(<generated>) ~[?:?]
	at godseye.cN.c(cN.java:132) ~[GodsEye.jar:?]
	at godseye.dr.onPacketReceiving(dr.java:143) ~[GodsEye.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:506) [ProtocolLib.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:245) [ProtocolLib.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[01:04:10] [Netty Server IO #1/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayInCustomPayload@7b062144[
    tag=minecraft:brand
    data=PooledUnsafeDirectByteBuf(ridx: 0, widx: 8, cap: 8)
  ]
[01:04:10] [Server thread/ERROR]: [GodsEye] Unhandled exception occured in onPacketSending(PacketEvent) for GodsEye
java.lang.UnsupportedOperationException: The method getAllowFlight is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$72f69d40.getAllowFlight(<generated>) ~[?:?]
	at godseye.cN.c(cN.java:132) ~[GodsEye.jar:?]
	at godseye.dr.onPacketSending(dr.java:149) ~[GodsEye.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:185) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:155) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1394) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1367) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.internalTeleport(PlayerConnection.java:1113) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1057) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1041) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1032) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:165) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:154) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:220) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1091) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot.jar:git-Spigot-56f8471-ccd47a5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[01:04:10] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayOutPosition@4114cd08[
    a=-1821.754453286356
    b=61.0
    c=-4411.472699890071
    d=-268.21063
    e=12.450056
    f=[]
    g=1
  ]

**Comment by Nort721** [comment]
Hey, please do not ignore the issue template when reporting an issue

An issue should contain the following:

1) GodsEye version
2) Server Version+Fork
3) ProtocolLib version
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue

Also please use Pastebin when sending a stacktrace of this size

Please open a new issue and follow these guidelines this time!
